export const CANDIDATES_REQUEST = "CANDIDATES_REQUEST";
export const CANDIDATES_SUCCESS = "CANDIDATES_SUCCESS";
export const CANDIDATES_ERROR = "CANDIDATES_ERROR";
export const CANDIDATE_UPDATE_REQUEST = "CANDIDATE_UPDATE_REQUEST";
export const CANDIDATE_UPDATE_SUCCESS = "CANDIDATE_UPDATE_SUCCESS";
export const CANDIDATE_UPDATE_ERROR = "CANDIDATE_UPDATE_ERROR";
